# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - gh-readonly-queue/*
pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "SourceBranchName: $(Build.SourceBranchName)"
    echo "SourceBranchName: $(Build.SourceBranch)"
    echo "PR Source Branch: $(System.PullRequest.SourceBranch)"
  displayName: 'Display branch information'

- script: npm test
  displayName: Run tests
  condition: and(succeeded(), eq(startsWith(variables['System.PullRequest.SourceBranch'], 'publish/'), false))
