name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group: {}
  workflow_dispatch: {}

jobs:
  do-something:
    name: Checks stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Display info"
        run: echo "${{ toJson(github) }}"
      - name: Test
        run: npm test